const std = @import("std");
const source = @import("../source/root.zig");
const trivia_mod = @import("trivia.zig");

pub const ownership_keywords = [_][]const u8{
    "read",
    "edit",
    "take",
    "hold",
};

pub const reference_qualifiers = [_][]const u8{
    "&read",
    "&edit",
    "&take",
    "&hold",
};

pub const lifetimes_are_explicit = true;
pub const regions_are_explicit = true;

pub const TokenKind = enum {
    identifier,
    lifetime_name,
    integer_literal,
    string_literal,
    char_literal,
    newline,
    indent,
    dedent,
    l_paren,
    r_paren,
    l_bracket,
    r_bracket,
    l_brace,
    r_brace,
    colon,
    comma,
    semicolon,
    dot,
    hash,
    bang,
    plus,
    minus,
    star,
    slash,
    percent,
    tilde,
    amp,
    pipe,
    caret,
    equal,
    eq_eq,
    bang_eq,
    arrow,
    fat_arrow,
    double_colon,
    lt,
    lte,
    gt,
    gte,
    lt_lt,
    gt_gt,
    amp_amp,
    pipe_pipe,
    range,
    range_inclusive,
    keyword_pub,
    keyword_package,
    keyword_mod,
    keyword_use,
    keyword_where,
    keyword_fn,
    keyword_suspend,
    keyword_const,
    keyword_struct,
    keyword_enum,
    keyword_trait,
    keyword_impl,
    keyword_union,
    keyword_extern,
    keyword_opaque,
    keyword_type,
    keyword_for,
    keyword_while,
    keyword_in,
    keyword_when,
    keyword_repeat,
    keyword_select,
    keyword_else,
    keyword_defer,
    keyword_break,
    keyword_continue,
    keyword_return,
    eof,
    unknown,
};

pub const Token = struct {
    kind: TokenKind,
    span: source.Span,
    lexeme: []const u8,
    leading_trivia: trivia_mod.TriviaRange = .{},
    trailing_trivia: trivia_mod.TriviaRange = .{},
};
